stages:
  - test and code analysis
  - build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

.configuration:
  image: ubuntu:20.04
  before_script:
    - apt-get update -qq &&
      apt-get install -y
      python3
      python3-pip
    - python3 -V
    - mkdir artifacts

.configuration-deployement:
  image: alpine:latest
  stage: deploy
  needs: [ "Build and push docker image" ]
  script:
    - echo [ Deploying to $CI_ENVIRONMENT_NAME started. Port=$BACKEND_PORT ]
    - chmod 400 $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $CI_ENVIRONMENT_NAME|| true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $BACKEND_PORT:$BACKEND_PORT -e ENV_FOR_DYNACONF=$CI_ENVIRONMENT_NAME --restart always --name $CI_ENVIRONMENT_NAME $TAG_COMMIT"
  environment:
    url: http://$SERVER_IP:$BACKEND_PORT
  when: manual

#==============================| TESTS AND CODE ANALYSIS |==============================

Lint code:
  stage: test and code analysis
  extends: .configuration
  allow_failure: true
  script:
    - echo [ Running pylint ]
    - pip install .
    - find . -type f -name "*.py" | xargs pylint

Check code using black:
  stage: test and code analysis
  extends: .configuration
  allow_failure: true
  script:
    - echo [ Running black ]
    - pip install black~=22.1.0
    - black . --check --diff --color

Launch tests:
  stage: test and code analysis
  extends: .configuration
  script:
    - echo [ Testing the steam-deals backend ]
    - apt-get install -y git
    - pip install .
    - python3 -m pytest tests/
      --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - artifacts/

#==============================| BUILD |==============================

Build and push docker image:
  image: docker:latest
  stage: build
  needs: [ "Launch tests" ]
  services:
    - docker:dind
  script:
    - echo [ Building a docker image started. ]
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - develop
    - master

#==============================| DEPLOY |==============================

Deploy to azure DEVELOPMENT server:
  extends: .configuration-deployement
  environment:
    name: DEVELOPMENT
  only:
    - develop

Deploy to azure PRODUCTION server:
  extends: .configuration-deployement
  environment:
    name: PRODUCTION
  only:
    - master
