FROM ubuntu:20.04

RUN \
    apt-get update && \
    apt-get install -y \
      python3 \
      python3-pip \
      python3-venv \
      git

ADD . /app
WORKDIR /app

RUN python3 -m venv venv/
ENV PATH="venv/bin:$PATH"

RUN make build

CMD ENVIRONMENT_NAME=PRODUCTION steam-deals
