[default]
LOG_LEVEL = 'info'
PROJECT_TITLE = 'steam-deals project backend API 🚀'
PROJECT_DESC = 'project carried out during `application development tools` classes.'
HOST = '0.0.0.0'


[development]
DEBUG = true
PORT = 5555
ALLOW_ORIGINS = [
    'http://localhost:8080',
    'https://localhost:8080',
    'http://nwta.eastus.cloudapp.azure.com:8080',
    'https://nwta.eastus.cloudapp.azure.com:8080',
]
DATABASE_URL = 'postgresql://postgres:devdevdev@localhost:5432/steam_deals_local'


[testing]
DEBUG = true
PORT = 5556
ALLOW_ORIGINS = ['http://localhost:8080', 'https://localhost:8080']
DATABASE_URL = 'sqlite:///./sqlite.db'


[production]
DEBUG = false
PORT = 5000
ALLOW_ORIGINS = ['http://nwta.eastus.cloudapp.azure.com', 'https://nwta.eastus.cloudapp.azure.com']
DATABASE_URL = '@format postgresql://{env[DB_USER]}:{env[DB_PASS]}@nwta.eastus.cloudapp.azure.com:5432/steam_deals'
