[default]
LOG_LEVEL = 'DEBUG'
PROJECT_TITLE = 'steam-deals project backend API 🚀'
PROJECT_DESC = 'project carried out during `application development tools` classes.'
ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 30
HOST = '0.0.0.0'
DNS = 'http://nwta.eastus.cloudapp.azure.com'
MAIL_PORT = 587
MAIL_SERVER = "smtp.gmail.com"
MAIL_TLS = true
MAIL_SSL = false
MAIL_USER_CREDENTIALS = true
REQUIRE_MAIL_CONFIRMATION = false


[development_local]
PORT = 5555
DNS = '0.0.0.0'
ALLOW_ORIGINS = ['http://0.0.0.0:8080', 'https://0.0.0.0:8080', 'http://localhost:8080', 'https://localhost:8080']
DATABASE_URL = '@format postgresql://{this.DB_USER}:{this.DB_PASS}@localhost:5432/steam_deals_local'
REQUIRE_MAIL_CONFIRMATION = true


[development]
PORT = 5555
ALLOW_ORIGINS = ['http://nwta.eastus.cloudapp.azure.com:8080', 'https://nwta.eastus.cloudapp.azure.com:8080']
DATABASE_URL = '@format postgresql://{this.DB_USER}:{this.DB_PASS}@localhost:5432/steam_deals_local'


[testing]
PORT = 5556
ALLOW_ORIGINS = ['http://0.0.0.0:8080', 'https://0.0.0.0:8080', 'http://localhost:8080', 'https://localhost:8080']
DATABASE_URL = 'sqlite:///./sqlite.db'


[production]
DEBUG = false
PORT = 5000
ALLOW_ORIGINS = ['http://nwta.eastus.cloudapp.azure.com', 'https://nwta.eastus.cloudapp.azure.com']
DATABASE_URL = '@format postgresql://{this.DB_USER}:{this.DB_PASS}@nwta.eastus.cloudapp.azure.com:5432/steam_deals'
REQUIRE_MAIL_CONFIRMATION = true
