[default]
LOG_LEVEL = 'info'
PROJECT_TITLE = 'steam-deals project backend API 🚀'
PROJECT_DESC = 'project carried out during `application development tools` classes.'
HOST = 'localhost'
DEBUG = true
PORT = 5555
ALLOW_ORIGINS = ['http://localhost:8080']

[development]

[testing]

[production]
DEBUG = false
PORT = 5000
ALLOW_ORIGINS = ['http://localhost']
